# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=30)),
                ('name_fr', models.CharField(max_length=30)),
                ('short_bio_ar', models.CharField(max_length=500)),
                ('short_bio_fr', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ar', models.CharField(blank=True, max_length=1000)),
                ('pub_date', models.DateField(blank=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hkaya.Character')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=100)),
                ('synopsis_ar', models.CharField(blank=True, max_length=500)),
                ('pub_date', models.DateField()),
                ('draft', models.IntegerField(default=1)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hkaya.Category')),
            ],
        ),
        migrations.AddField(
            model_name='response',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hkaya.Story'),
        ),
    ]
