# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hkaya', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='character',
            name='short_bio_fr',
        ),
    ]
