# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import hkaya.models


class Migration(migrations.Migration):

    dependencies = [
        ('hkaya', '0003_character_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='photo',
            field=models.ImageField(blank=True, upload_to=hkaya.models.user_directory_path),
        ),
    ]
